#! /usr/bin/env bash

function usage {
  echo "Usage: aoc [DIRECTORY]"
}

docker images | grep aoc23 > /dev/null 2>&1 || docker build . -t aoc23:latest

if [ -z "$1" ]
then
  usage
  exit 1
fi

docker run -v `pwd`/$1:/workspace aoc23 go run main.go
